# Generated by Django 6.0.7 on 2026-07-28 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_customers(apps, schema_editor):
    Order = apps.get_model('accounts', 'Order')
    Customer = apps.get_model('accounts', 'Customer')
    for order in Order.objects.all():
        # Use the old fields (which still exist at this point)
        customer, created = Customer.objects.get_or_create(
            user=order.user,
            name=order.client_name,
            phone=order.contact_number,
            defaults={
                'address': order.delivery_address,
                'email': '',
                'notes': 'Auto-created from order'
            }
        )
        order.customer = customer
        order.save(update_fields=['customer'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_orderitem'),
    ]

    operations = [
        # 1️⃣ Create the Customer table
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phone')},
            },
        ),

        # 2️⃣ Add the foreign key to Order (nullable for now)
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customer'),
        ),

        # 3️⃣ Backfill data: copy old fields into Customer and link
        migrations.RunPython(backfill_customers),

        # 4️⃣ Now it's safe to remove the old fields
        migrations.RemoveField(
            model_name='order',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
    ]