# Generated by Django 6.0.7 on 2026-07-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_order_client_name_remove_order_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
